### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by tancyit3** [shamhi/XPointsMakerBot#3]
```
  File "D:\bots\main.py", line 4, in <module>
    from core.registrator import *
  File "D:\bots\\core\registrator.py", line 128
    logger.info(f"{user_data[index]['username'][:15].ljust(
                ^
SyntaxError: unterminated string literal (detected at line 128)
```

Из-за чегор возникает ошибка?
AUTO_BET = False
В proxy.txt - none
сессия в data стоит

**Comment by WanterDehka** [comment]
Похоже у всех такая ошибка

**Comment by MelikUltra** [comment]
I have the same error too , i tried almost everything changing this and that with proxy without proxy editing config nothing worked

**Comment by Domenick90** [comment]
У меня на версии питона 3.11.9 тоже такая ошибка, на 3.12 работает!

**Comment by MelikUltra** [comment]
> У меня на версии питона 3.11.9 тоже такая ошибка, на 3.12 работает!

like all you did was pasting user data right ? was it need to paste user-agent also ?
did you use proxy ?

**Comment by Domenick90** [comment]
> like all you did was pasting user data right ? was it need to paste user-agent also ?
> did you use proxy ?

Proxy - None, user-agent - None. Yes, im using only user data (started from query_id=XXXX)

**Comment by Mahmooden10** [comment]
i have same problem

**Comment by MelikUltra** [comment]
> > like all you did was pasting user data right ? was it need to paste user-agent also ?
> > did you use proxy ?
> 
> Proxy - None, user-agent - None. Yes, im using only user data (started from query_id=XXXX)

that was helpfult brother thanks for the reply, i managed to run it using python 3.10 but i dont even remember what i did

**Comment by Pawansingh333** [comment]
same

**Comment by AlexArGC** [comment]
Used Python 3.12
