### ISSUE TITLE
Bot not run after authorization successfull

### ISSUE THREAD

**Issue by khosrowkhazraei** [shamhi/XPointsMakerBot#5]
24-08-21 14:17:54 | WARNING  | 13   - System | Random wait 0-3 sec to authorization!
24-08-21 14:17:54 | INFO     | 32   - System | List [1] session is loaded...
24-08-21 14:17:54 | SUCCESS  | 86   - System | List [1] proxy  download...
24-08-21 14:17:54 | SUCCESS  | 55   - System | List [1] user-agent download...
24-08-21 14:18:01 | INFO     | 97   - User-Name | id [0] | IP: 103.143.204.100 - Herāt,AF | wait 2 sec
24-08-21 14:18:04 | SUCCESS  | 106  - User-Name| Authorization successful.
Traceback (most recent call last):
  File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\main.py", line 32, in <module>
    asyncio.run(main())
  File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\main.py", line 26, in main
    await asyncio.gather(*tasks)
  File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 111, in start
    await parse_profile(profile_data, index)
  File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 57, in parse_profile
    user_data[index]['level'] = profile_data['currentLevel']['level']

**Comment by MelikUltra** [comment]
> 24-08-21 14:17:54 | WARNING | 13 - System | Random wait 0-3 sec to authorization! 24-08-21 14:17:54 | INFO | 32 - System | List [1] session is loaded... 24-08-21 14:17:54 | SUCCESS | 86 - System | List [1] proxy download... 24-08-21 14:17:54 | SUCCESS | 55 - System | List [1] user-agent download... 24-08-21 14:18:01 | INFO | 97 - User-Name | id [0] | IP: 103.143.204.100 - Herāt,AF | wait 2 sec 24-08-21 14:18:04 | SUCCESS | 106 - User-Name| Authorization successful. Traceback (most recent call last): File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\main.py", line 32, in asyncio.run(main()) File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\main.py", line 26, in main await asyncio.gather(*tasks) File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 111, in start await parse_profile(profile_data, index) File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 57, in parse_profile user_data[index]['level'] = profile_data['currentLevel']['level']

dont worry brother im here to help 
<img width="664" alt="Xpoint" src="https://github.com/user-attachments/assets/024e64d9-9b50-470a-8c8a-25f7fe1b32f0">


go to inspecter and copy paste your user-agent to the user-agent.txt but make user to delete the old one and also update your query_id and if you run multiple account IF it didnt work make as much as user-agent as your account equally

**Comment by AlexArGC** [comment]
> 24-08-21 14:17:54 | WARNING | 13 - System | Random wait 0-3 sec to authorization! 24-08-21 14:17:54 | INFO | 32 - System | List [1] session is loaded... 24-08-21 14:17:54 | SUCCESS | 86 - System | List [1] proxy download... 24-08-21 14:17:54 | SUCCESS | 55 - System | List [1] user-agent download... 24-08-21 14:18:01 | INFO | 97 - User-Name | id [0] | IP: 103.143.204.100 - Herāt,AF | wait 2 sec 24-08-21 14:18:04 | SUCCESS | 106 - User-Name| Authorization successful. Traceback (most recent call last): File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\main.py", line 32, in asyncio.run(main()) File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Khosrow\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\main.py", line 26, in main await asyncio.gather(*tasks) File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 111, in start await parse_profile(profile_data, index) File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 57, in parse_profile user_data[index]['level'] = profile_data['currentLevel']['level']

did you solve the problem?

**Comment by AlexArGC** [comment]
> File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 111, in start
> await parse_profile(profile_data, index)
> File "C:\Users\Khosrow\Desktop\Final Update Bot\XPointsMakerBot\core\registrator.py", line 57, in parse_profile
> user_data[index]['level'] = profile_data['currentLevel']['level']

did you solve the problem?

**Comment by khosrowkhazraei** [comment]
@AlexArGC 
Not yet, I checked all with queryid and user agent, but no way 

I think the issue is in the response of user data after passing session and index to the function in register.py 

Thank you for your follow up

**Comment by AlexArGC** [comment]
Maybe your country is blocked? There is too little data to give advice. Libraries are made of requirements.txt ?

**Comment by khosrowkhazraei** [comment]
I can run the bot web as well as in PC and mobile in the same network.
So there is no blocking issue and all the required libraries are fully
installed. The only thing I noticed is the login session response is not
valid and I am not good at python to figure it out

**Comment by khosrowkhazraei** [comment]
Here is screnshot that shows all the requirments, if i missed anything plase guide. 
![image](https://github.com/user-attachments/assets/d33701b0-5116-4b0f-ab4d-034c7eee8f74)

**Comment by AlexArGC** [comment]
Install pycharm and run of debugger ?
It`s new accaunt from 0 level?

**Comment by khosrowkhazraei** [comment]
It is new but had some clicks. Will share you log of debug as well.

Thank you

**Comment by AlexArGC** [comment]
commit d339ce7
